SMS.Web/Controllers/StudentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SMS.Data.Entities;
using SMS.Data.Services;

using SMS.Web.Models;

namespace SMS.Web.Controllers;

[Authorize]
public class StudentController : BaseController
{
    private IStudentService svc;
    
    public StudentController(IStudentService _svc)
    { 
        svc = _svc;
    }

    // GET /student
    public IActionResult Index(string order="id", string direction="asc")
    {
        // load students using service and pass to view
        var data = svc.GetStudents(order);
        
        return View(data);
    }

    // GET /student/details/{id}
    public IActionResult Details(int id)
    {
        var student = svc.GetStudent(id);
      
        // check if student is null and alert/redirect 
        if (student is null) {
            Alert("Student not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }
        return View(student);
    }

    // GET: /student/create
    [Authorize(Roles="admin,support")]
    public IActionResult Create()
    {
        // display blank form to create a student
        return View();
    }

    // POST /student/create
    [Authorize(Roles="admin,support")]
    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Create([Bind("Name, Email, Course, Dob, Grade, PhotoUrl")] Student s)
    {   
        // validate email is unique
        if (svc.GetStudentByEmail(s.Email) != null)
        {
            ModelState.AddModelError(nameof(s.Email), "The email address is already in use");
        } 

        // complete POST action to add student
        if (ModelState.IsValid)
        {
            // call service AddStudent method using data in s
            var student = svc.AddStudent(s);
            if (student is null) 
            {
                Alert("Issue creating the student", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Details), new { Id = student.Id});   
        }
        
        // redisplay the form for editing as there are validation errors
        return View(s);
    }

    // GET /student/edit/{id}
    [Authorize(Roles="admin,support")]
    public IActionResult Edit(int id)
    {
        // load the student using the service
        var student = svc.GetStudent(id);

        // check if student is null and Alert/Redirect
        if (student is null)
        {
            Alert("Student not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }  

        // pass student to view for editing
        return View(student);
    }

    // POST /student/edit/{id}
    [ValidateAntiForgeryToken]
    [Authorize(Roles="admin,support")]
    [HttpPost]
    public IActionResult Edit(int id, Student s)
    {
        // check if email exists and is not owned by student being edited 
        var existing = svc.GetStudentByEmail(s.Email);
        if (existing != null && s.Id != existing.Id) 
        {
           ModelState.AddModelError(nameof(s.Email), "The email address is already in use");
        } 

        // complete POST action to save student changes
        if (ModelState.IsValid)
        {            
            var student = svc.UpdateStudent(s);
            if (student is null) 
            {
                Alert("Issue updating the student", AlertType.warning);
            }

            // redirect back to view the student details
            return RedirectToAction(nameof(Details), new { Id = s.Id });
        }

        // redisplay the form for editing as validation errors
        return View(s);
    }

    // GET / student/delete/{id}
    [Authorize(Roles="admin")]      
    public IActionResult Delete(int id)
    {
        // load the student using the service
        var student = svc.GetStudent(id);
        // check the returned student is not null and if so return NotFound()
        if (student == null)
        {
            Alert("Student not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }     
        
        // pass student to view for deletion confirmation
        return View(student);
    }

    // POST /student/delete/{id}
    [HttpPost]
    [Authorize(Roles="admin")]
    [ValidateAntiForgeryToken]   
    public IActionResult DeleteConfirm(int id)
    {
        // delete student via service
        var deleted = svc.DeleteStudent(id);
        if (deleted)
        {
            Alert("Student deleted", AlertType.success);            
        }
        else
        {
            Alert("Student could not  be deleted", AlertType.warning);           
        }
        
        // redirect to the index view
        return RedirectToAction(nameof(Index));
    }

    // ============== Student ticket management ==============

    // GET /student/ticketcreate/{id}
    public IActionResult TicketCreate(int id)
    {
        var student = svc.GetStudent(id);
        if (student == null)
        {
            Alert("Student not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }

        // create a ticket view model and set foreign key
        var ticket = new Ticket { StudentId = id }; 
        // render blank form
        return View( ticket );
    }

    // POST /student/ticketcreate
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult TicketCreate([Bind("StudentId, Issue")] Ticket t)
    {
        if (ModelState.IsValid)
        {                
            var ticket = svc.CreateTicket(t.StudentId, t.Issue);
            Alert($"Ticket created successfully for student {t.StudentId}", AlertType.info);            
            // redirect to display student - note how Id is passed
            return RedirectToAction(
                nameof(Details), new { Id = ticket.StudentId }
            );
        }
        // redisplay the form for editing
        return View(t);
    }

     // GET /student/ticketedit/{id}
    public IActionResult TicketEdit(int id)
    {
        var ticket = svc.GetTicket(id);
        if (ticket == null)
        {
            Alert($"Ticket {id} not found", AlertType.warning);
            return RedirectToAction(nameof(Index));
        }        
        return View( ticket );
    }

    // POST /student/ticketedit
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult TicketEdit(int id, [Bind("StudentId, Issue")] Ticket t)
    {
        if (ModelState.IsValid)
        {                
            var ticket = svc.UpdateTicket(id, t.Issue);
            return RedirectToAction(
                nameof(Details), new { Id = ticket.StudentId }
            );
        }
        // redisplay the form for editing
        return View(t);
    }

    // GET /student/ticketdelete/{id}
    public IActionResult TicketDelete(int id)
    {
        // load the ticket using the service
        var ticket = svc.GetTicket(id);
        // check the returned Ticket is not null and if so return NotFound()
        if (ticket == null)
        {
            Alert("Ticket not found", AlertType.warning);
            return RedirectToAction(nameof(Index));;
        }     
        
        // pass ticket to view for deletion confirmation
        return View(ticket);
    }

    // POST /student/ticketdeleteconfirm/{id}
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult TicketDeleteConfirm(int id, int studentId)
    {
        // delete ticket via service
        var deleted = svc.DeleteTicket(id);
        if (deleted)
        {
            Alert("Ticket deleted", AlertType.success);            
        }
        else
        {
            Alert("Ticket could not  be deleted", AlertType.warning);           
        }

        // redirect to the student details view
        return RedirectToAction(nameof(Details), new { Id = studentId });
    }

    // ============================= Module Management ==============================

        // GET /student/updatemodule/{id}
        [Authorize(Roles = "admin")]
        public IActionResult ModuleUpdate(int id)
        {
            var sm = svc.GetStudentModule(id);  
            if (sm == null)
            {
                Alert("Student Module Not Found", AlertType.warning);
                return RedirectToAction(nameof(Details));
            }
            var vm = new StudentModuleViewModel {
                StudentId = sm.StudentId,
                ModuleId = sm.ModuleId,
                Mark = sm.Mark
            };            
            return View( vm );
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public IActionResult ModuleUpdate(StudentModuleViewModel sm)
        {
            if (ModelState.IsValid)
            {                
                svc.UpdateStudentModuleMark(sm.StudentId, sm.ModuleId, sm.Mark);

                return RedirectToAction(nameof(Details), new { Id = sm.StudentId });
            }
            // redisplay the form for editing
            return View(sm);
        }

        // GET /student/moduleadd/{id}
        [Authorize(Roles = "admin")]
        public IActionResult ModuleAdd(int id)
        {
            var sm = svc.GetStudent(id);  
            if (sm == null)
            {
                Alert("StudentNot Found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }  

            var modules = svc.GetAvailableModulesForStudent(id);  
            var vm = new StudentModuleViewModel {
                Modules = new SelectList(modules,"Id","Title"),
                StudentId = id
            };  
            return View(vm);
        }

        [HttpPost]
        [Authorize(Roles = "admin")]
        [ValidateAntiForgeryToken]
        public IActionResult ModuleAdd(StudentModuleViewModel sm)
        {
            if (ModelState.IsValid)

SMS.Web/Controllers/TicketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

using SMS.Data.Entities;
using SMS.Data.Services;

using SMS.Web.Models;

namespace SMS.Web.Controllers;

[Authorize]
public class TicketController : BaseController
{
    private readonly IStudentService svc;

    public TicketController()
    {
        svc = new StudentServiceDb();
    } 
     
    // GET/POST /ticket/index
    public IActionResult Index(TicketSearchViewModel search)
    {                  
        // set the viewmodel Tickets property by calling service method 
        // using the range and query values from the viewmodel 
        search.Tickets = svc.SearchTickets(search.Range, search.Query, search.OrderBy, search.Direction);

        // build custom alert message                
        var alert = $"{search.Tickets.Count} result(s) found searching '{search.Range}' Tickets";
        if (search.Query != null )
        {
            alert += $" for '{search.Query}'"; 
        }
        // display alert
        Alert(alert, AlertType.info);         
        
        return View(search);
    } 

    // display page containg JS query 
    public IActionResult Search()
    {
        return View();
    }

    [AllowAnonymous]
    // GET /tickets/query
    [HttpGet("api/ticket/search")]
    public IActionResult Search(string query, TicketRange range=TicketRange.ALL)
    {    
        // search tickets   
        var tickets = svc.SearchTickets(range, query);
        // map tickets to custom DTO object
        var data = tickets.Select( t => new {   
            Id = t.Id,
            Issue = t.Issue, 
            CreatedOn = t.CreatedOn,
            Active = t.Active,
            Student = t.Student?.Name
        });
        // return json containing custom tickets list
        return Ok(data);
    } 
                    
    // GET/ticket/{id}
    public IActionResult Details(int id)
    {
        var ticket = svc.GetTicket(id);
        if (ticket == null)
        {
            Alert("Ticket Not Found", AlertType.warning);  
            return RedirectToAction(nameof(Index));             
        }

        return View("Details",ticket);
    }

    [HttpPost]
    [Authorize(Roles="admin,support")]
    public IActionResult Open(int id)
    {
        svc.OpenTicket(id);
        return RedirectToAction(nameof(Details), new { Id = id });
    }
    
    // POST /ticket/close/{id}
    [HttpPost]
    [Authorize(Roles="admin,support")]
    public IActionResult Close([Bind("Id, Resolution")] Ticket t)
    {
        // close ticket via service
        var ticket = svc.CloseTicket(t.Id, t.Resolution);
        if (ticket == null)
        {
            Alert("Ticket Not Found", AlertType.warning);                               
        }
        else
        {
            Alert($"Ticket {t.Id } closed", AlertType.info);  
        }

        // redirect to the index view
        return RedirectToAction(nameof(Details), new { Id = t.Id });
    }
    
    // GET /ticket/create
    [Authorize(Roles="admin,support")]
    public IActionResult Create()
    {
        var students = svc.GetStudents();
        // populate viewmodel select list property
        var tvm = new TicketCreateViewModel {
            Students = new SelectList(students,"Id","Name") 
        };
        
        // render blank form
        return View( tvm );
    }
    
    // POST /ticket/create
    [HttpPost]
    [Authorize(Roles="admin,support")]
    public IActionResult Create(TicketCreateViewModel tvm)
    {
        if (ModelState.IsValid)
        {
            svc.CreateTicket(tvm.StudentId, tvm.Issue);
    
            Alert($"Ticket Created", AlertType.info);  
            return RedirectToAction(nameof(Index));
        }
        
        // redisplay the form for editing
        return View(tvm);
    }

}

SMS.Web/Views/Shared/_Alert.cshtml
@{
    string message = (string)TempData["Alert.Message"];
    string type    = (string)TempData["Alert.Type"];
}

@if (message != null && type != null)
{
    <div class="alert alert-@type alert-dismissible fade show my-4" role="alert" aria-label="@type">            
        @message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>    
}

SMS.Web/Views/Shared/_AlertIcons.cshtml
@{
    string message = (string)TempData["Alert.Message"];
    string type    = (string)TempData["Alert.Type"];
}

<!-- svg icon definitions -->
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="icon-success" fill="currentColor" viewBox="0 0 16 16">
    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
  </symbol>
  <symbol id="icon-info" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
  </symbol>
  <symbol id="icon-warning" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
  <symbol id="icon-danger" fill="currentColor" viewBox="0 0 16 16">
    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
  </symbol>
</svg>

<!-- only display alert if message and type are set -->
@if (message != null && type != null)
{
    <div class="alert alert-@type alert-dismissible fade show" role="alert">
        <div>
            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="@type">
                <!-- select svg icon based on alert type -->       
                <use href="#icon-@type"/>   
            </svg>
            @message
        </div>
       
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>    

  <script>      
      // set a time out to remove any node with an alert class after 2 seconds
      setTimeout(() => {          
          new bootstrap.Alert(document.querySelector('.alert')).close()
      }, 2000);
  </script>
}

SMS.Web/Views/Shared/_BasicLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>

    <nav class="mb-4">           
        <div class="d-flex gap-4 bg-light p-2 rounded-2 align-items-baseline">
            <span class="fs-4 fw-bolder">SMS</span>  
           
            <a class="fw-bold text-dark text-decoration-none hover-effect" asp-controller="Home" asp-action="Index">Home</a>    
            <a class="fw-bold text-dark text-decoration-none hover-effect" asp-controller="Home" asp-action="About">About</a>    
            <a class="fw-bold text-dark text-decoration-none hover-effect" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <a class="fw-bold text-dark text-decoration-none hover-effect" asp-controller="Student" asp-action="Index">Students</a>
            <a class="fw-bold text-dark text-decoration-none hover-effect" asp-controller="Ticket" asp-action="Index">Tickets</a>
        </div>       
    </nav>
    
    <div class="container my-4">
        <!-- render the alert partial -->
        <partial name="_AlertIcons" />

        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="bottom border-top w-100 bg-light py-2 mt-5 text-muted text-center">
        &copy; 2023 - SMS.Web 
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SMS.Web/Views/Shared/_BreadCrumbs.cshtml
<!-- model contains array of breadcrumb tuples (link,crumb) -->
@model IList<(string,string)>

@if (Model != null ) {
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      @foreach(var (link,crumb) in Model)
      {
          @if (link == null || link.Length == 0)
          {
              <li class="breadcrumb-item active" aria-current="page">@crumb</li>
          }
          else
          {
              <li class="breadcrumb-item"><a href="@link">@crumb</a></li>
          }
      }
    </ol>
  </nav>
}

SMS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>SMS.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <!-- Toggler - responsive navbar https://getbootstrap.com/docs/5.1/components/navbar/#toggler -->
        <nav class="navbar navbar-expand-md navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand text-primary fw-bold" href="#">SMS</a>  
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                   
                    <!-- login partial -->
                    <partial name="_LoginPartial"/>
                 
                   <!-- Menu Items -->
                    <ul class="navbar-nav me-auto my-1 my-lg-0 fw-normal"> 

                        <li class="nav-item">
                            <a class="nav-link text-dark hover-effect" asp-controller="Home" asp-action="Index">Home</a>
                        </li>  

                        <li asp-condition=@(User.Identity.IsAuthenticated) class="nav-item">
                            <a class="nav-link text-dark hover-effect" asp-controller="Student" asp-action="Index">Students</a>
                        </li>

                        <li asp-condition=@(User.Identity.IsAuthenticated) class="nav-item">
                            <a class="nav-link text-dark hover-effect" asp-controller="Ticket" asp-action="Index">Tickets</a>
                        </li>

                        <!-- combine Privacy and About into a single drop down titled Company -->                     
                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle hover-effect" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Company</a>
                            <ul class="dropdown-menu">
                                <li> <a class="dropdown-item" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                                <li> <a class="dropdown-item" asp-controller="Home" asp-action="About">About</a></li>
                            </ul>
                        </li>  
                    </ul> 
                </div>
            </div>
        </nav>
    </header>

    <div class="container my-4">
        <!-- render the alert partial -->
        <partial name="_AlertIcons" />

        <main role="main">
            @RenderBody()
        </main>

    </div>

    <footer class="bottom border-top w-100 bg-light py-2 mt-5 text-muted text-center">
        &copy; 2023 - SMS.Web 
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>